stages: 
  - build
  - test
  - deploy

build-job:
  stage: build
  tags:
    - build
    - deploy 
  script:
    - echo "Compiling the code..."
    - echo "Compile complete"

unit-test-job:
  image: python:3.11-bookworm
  stage: test
  tags:
    - build
    - deploy 
  before_script: 
    - apt-get update && apt-get install make
  script:
    - make venv && make test

lint-test-job:
  #image: python:3.11-bookworm
  stage: test
  tags:
    - build
    - deploy 
  before_script: 
    - apt-get update && apt-get install make
  script: 
    # - make venv && make lint-fix
    - echo "Lint initiated"
    - echo "lint complete"

deploy-job:
  stage: deploy
  tags:
    - build
    - deploy 
  script:
    - echo "Deploying application"
    - echo "Application deployed successfully"
