service: lambda-webhook

provider:
  name: aws
  runtime: python3.9
  environment:
    TWILIO_AUTH_TOKEN: YOUR_TWILIO_AUTH_TOKEN

plugins:
  - serverless-wsgi
  - serverless-python-requirements

functions:
  webhook:
    handler: wsgi_handler.handler
    url: true

custom:
  wsgi:
    app: bot.app
  pythonRequirements:
    pythonBin: python
